### 1. Récupérer toutes les personnes (donateurs)
GET http://localhost:3000/api/personnes
Content-Type: application/json

### 
  
### ajouter un dépots
POST http://localhost:3000/api/depots
Content-Type: application/json

{
  "personne_id": 1,
  "date_depot": "2026-09-09"
}
 
### 

### 3. récupérer un dépôt par son ID 
GET http://localhost:3000/api/depots/1
Content-Type: application/json

###

###  route imbriqué
POST http://localhost:3000/api/depots/1/objets
Content-Type: application/json

{
  "categorie_id": 1,
  "libelle": "Vélo de ville",
  "poids_kg": 12.5,
  "etat_arrivee": "bon_etat",
  "statut": "arrive"
}
  "statut": "en_rayon",
  "prix": 85.00,
  "date_mise_rayon": "2026-08-31",
  "categorie_id": 2,
  "vente_id": null,
  "prix_paye": 0.00
}

###
PATCH http://localhost:3000/api/objets/1/statut

{
  "statut": "en_rayon",
  "prix": 1000.00,
},

###
GET http://localhost:3000/api/stats
###


GET http://localhost:3000/api/benevoles
